# Project information
site_name: User Management Service
docs_dir: zoomin_docs
nav:
  - Home: index.md
  - ApiDocs: api-docs/index.html

site_author: Shubham
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes – searchable, customizable, in 60+ languages, for all devices
# Repository
repo_name: theshubhamshivhare/cypressTest
repo_url: https://github.com/theshubhamshivhare/cypressTest

# Copyright
copyright: Copyright &copy; 2016 - 2024 Amdocs Platform X
