name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          npm install
      - name: Chrome Install
        run: |
          chrome_url=https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-123.0.6312.59-1.x86_64.rpm
          echo "DOWNLOAD CHROME URL: $chrome_url"
          requested_version="Google Chrome 123.0.6312.59-1"
          {
            if [[ $(which google-chrome) ]]; then
              echo "Google Chrome path"
              which google-chrome
              chrome_version="$(google-chrome --version)"
              echo "Installed chrome: $chrome_version"
            fi
            if [[ $chrome_version ]]; then
              echo "Installed version ($chrome_version) vs requested ($requested_version): $chrome_version != $requested_version"
              if [[ $chrome_version != $requested_version ]]; then
                sudo yum reinstall -y $chrome_url
              fi
            else
              sudo yum install -y $chrome_url
            fi
            if [[ ! $(chrome --version) ]]; then
              echo "Create <chrome> symlink"
              sudo ln -s $(which google-chrome) /usr/bin/chrome
            fi
          } || {
            sudo yum install -y $chrome_url
            if [[ ! $(chrome --version) ]]; then
              echo "Create <chrome> symlink"
              sudo ln -s $(which google-chrome) /usr/bin/chrome
            fi
          }
      - name: Check Chrome version
        run: chrome --version
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm run test-e2e
          wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud 
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          no_proxy: fs.amdocs.com,localhost,google.com,auth0.com
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: dist
