name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: theshubhamshivhare/Express-Boilerplate
          path: asmp-documentation
      
      - name: Create a new branch in Zoomin Repository
        id: create_branch
        run: |
          cd asmp-documentation
          BRANCH_NAME="feature-${{ github.ref_name }}"  # Create a branch name using the name of the feature branch
          git checkout -b $BRANCH_NAME
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Sync source to target repository
        run: |
          rsync -av --progress ./ asmp-documentation/ --exclude .git --exclude .github

      - name: Commit changes and Push
        run: |
          cd asmp-documentation
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          git status
          git add .
          git commit -m "Sync from user-management repository"

          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)  # Get the current branch name
          echo "Pushing changes to branch $BRANCH_NAME"
          git status
          git push origin HEAD  # Push changes to the newly created current branch
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Sync from user-management repository
          branch: test  # Use the dynamically created branch name
          base: master  # Base branch to merge into
          title: 'Sync from user-management repository'
          body: |
            This pull request is automatically created by GitHub Actions to sync changes from the user-management repository.
      
      
